module.exports = {
  content: [
    "./report/templates/**/*.html",
    "./report/static/app.js",
  ],
  safelist: [
    "badge-error",
    "badge-warning",
    "badge-success",
    "badge-ghost",
    "badge-info",
    "progress-error",
    "progress-warning",
    "progress-success",
    "progress-info",
    "bg-error/10",
    "bg-warning/10",
    "bg-success/10",
    "text-error",
    "text-warning",
    "text-success",
    "text-gh-gold",
    "text-gh-silver",
    "text-gh-bronze",
    "text-gh-muted",
    "text-gh-red",
    "text-gh-green",
    "text-gh-yellow",
    "text-gh-blue",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '"SFMono-Regular"',
          '"Cascadia Mono"',
          '"JetBrains Mono"',
          "Menlo",
          "Consolas",
          '"Sarasa Mono SC"',
          '"PingFang SC"',
          '"Microsoft YaHei"',
          "ui-monospace",
          "monospace",
        ],
        ui: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          '"Noto Sans"',
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          "sans-serif",
        ],
        mono: [
          '"SFMono-Regular"',
          '"Cascadia Mono"',
          '"Sarasa Mono SC"',
          '"JetBrains Mono"',
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          "monospace",
        ],
      },
      colors: {
        gh: {
          canvas: "#0d1117",
          inset: "#010409",
          subtle: "#161b22",
          overlay: "#1c2128",
          elevated: "#21262d",
          border: "#30363d",
          "border-muted": "#21262d",
          fg: "#e6edf3",
          muted: "#8b949e",
          faint: "#6e7681",
          blue: "#58a6ff",
          green: "#3fb950",
          red: "#f85149",
          yellow: "#d29922",
          purple: "#a371f7",
          gold: "#e3b341",
          silver: "#c9d1d9",
          bronze: "#d18616",
        },
        // Legacy palette remapped onto the GitHub dark scale.
        beige: {
          50: "#161b22",
          100: "#0d1117",
          200: "#30363d",
          300: "#484f58",
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        "github-dark": {
          "color-scheme": "dark",
          primary: "#58a6ff",
          "primary-content": "#0d1117",
          secondary: "#a371f7",
          "secondary-content": "#0d1117",
          accent: "#3fb950",
          "accent-content": "#0d1117",
          neutral: "#21262d",
          "neutral-content": "#e6edf3",
          "base-100": "#0d1117",
          "base-200": "#161b22",
          "base-300": "#21262d",
          "base-content": "#e6edf3",
          info: "#58a6ff",
          "info-content": "#0d1117",
          success: "#3fb950",
          "success-content": "#0d1117",
          warning: "#d29922",
          "warning-content": "#0d1117",
          error: "#f85149",
          "error-content": "#0d1117",
          "--rounded-box": "6px",
          "--rounded-btn": "6px",
          "--rounded-badge": "2em",
          "--border-btn": "1px",
          "--animation-btn": "0.15s",
          "--tab-radius": "6px",
        },
      },
    ],
  },
};